version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "buffalo dev"
    entrypoint: /vivo-scholar/docker-entrypoint.sh
    env_file:
      - ./.env
    volumes:
      - .:/vivo-scholar
      - go:/go
    ports:
      - "4200:4200"
volumes:
 go:
